---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r, echo = TRUE, warning=FALSE, comment=NA, message=FALSE}
library(ggplot2)
library(plyr); library(dplyr)
library(lubridate)
activity <- read.csv("activity.csv", header = TRUE, stringsAsFactors = FALSE)
activity$date <- as.POSIXct(activity$date, format = "%Y-%m-%d")
perday <- summarize(group_by(activity, date),total = sum(steps, na.rm = TRUE))
```

## What is mean total number of steps taken per day?

```{r, echo = TRUE, warning=FALSE, comment=NA}
cat("Mean:", mean(perday$total, na.rm = TRUE))
cat("Median:", median(perday$total, na.rm = TRUE))
ggplot(data = perday, aes(perday$total)) +
  geom_histogram(width = 2, bins = 15, col = "red") +
  theme_bw() +
  labs(x = "Steps per day", 
       y = "Number of days", 
       title = "Distribution of steps across 2 months") +
  xlim(c(0, 22000))
```  


## What is the average daily activity pattern?

```{r, echo = TRUE, warning=FALSE, comment=NA}
pattern <- activity %>% 
  group_by(interval) %>% 
  summarize(avg = mean(steps, na.rm = TRUE))
ggplot(data = pattern, aes(x = interval, y = avg)) +
  geom_line() +
  theme_bw() +
  xlim(c(0, 2355)) +
  labs(title = "Average daily pattern", x = "Time interval", y = "Steps")
print("The 5 minute interval with the maximum average value was:")
print(filter(pattern, avg == max(avg)))
```  

## Imputing missing values
#####If there is an NA, I will just the average value for that interval.
```{r, echo = TRUE, warning=FALSE, comment=NA}
cat("Number of rows with NAs is", sum(is.na(activity)))
#create new dataframe that will have impuned values
impune <- activity
#calculated average values for time intervals, to use for impuning
perint <- summarize(group_by(activity, interval), 
                    total = sum(steps, na.rm = TRUE), 
                    avg = mean(steps, na.rm = TRUE))
#for loop, to impune values in new dataset
for(i in 1:nrow(impune)){
  if(is.na(impune$steps[i])){
    impune$steps[i] <- perint$avg[which(impune$interval[i] == perint$interval)]
  }
}
perdayimpune <- summarize(group_by(impune, date),total = sum(steps))
ggplot(data = perdayimpune, aes(perdayimpune$total)) +
  geom_histogram(width = 2, bins = 15, col = "red") +
  theme_bw() +
  labs(x = "Steps per day", 
       y = "Number of days", 
       title = "Distribution of steps across 2 months, with missing data impuned") +
  xlim(c(0, 22000))
cat("New mean:", mean(perdayimpune$total, na.rm = TRUE))
cat("New median:", median(perdayimpune$total, na.rm = TRUE))
print("After impuning missing data with this method, both mean and median steps taken per day go up.")
```


## Are there differences in activity patterns between weekdays and weekends?

```{r, echo = TRUE, warning=FALSE, comment=NA}
impune$dow <- 0
impune$weekend <- 0
#a for loop to add in days of week
for(i in 1:nrow(impune)){
  impune$dow[i] <- wday(impune$date[i], label = TRUE, abbr = FALSE)
  ifelse(impune$dow[i] == 1 | impune$dow[i] == 7, impune$weekend[i] <- TRUE, impune$weekend[i] <- FALSE)
}
#for day of the week, 1 is Sunday, 7 is Saturday

#here I'm going to create two dataframes containing the averages for weekdays and weekends respectively, then I'll rbind them together, after cbinding in something to let me distinguish between them

MonFriavg <- filter(impune, weekend == TRUE) %>% 
  group_by(interval) %>% 
  summarize(avg = mean(steps, na.rm = TRUE))

SatSunavg <- filter(impune, weekend == FALSE) %>% 
  group_by(interval) %>% 
  summarize(avg = mean(steps, na.rm = TRUE))

allavg <- rbind(
  cbind(MonFriavg, dow = "Weekday"),
  cbind(SatSunavg, dow = "Weekend")
)

ggplot(allavg, aes(x = interval, y = avg)) +
  facet_wrap(~dow, nrow = 1) +
  geom_line()+
  theme_bw() +
  labs(x = "Interval", 
       y = "Number of steps per interval", 
       title = "How activity differs from weekdays to weekends")
```
